<style>
<!--
 .tableWindow{ border:thin solid #33A39D;width:100%;}
 .tableLarge{ width:100%;}
 .tableSmall{ width:100%;}
 .tdCal { background-color:#FFFFFF;font:arial;font-weight:bold;color:#000000;font-size:smaller;	border:thin solid #DDDDFF; }
 .tdCal a{ color:#000000;font-size:smaller;	}
 .thCal { background-color:#FFFFEE;font:arial;font-weight:bold;color:#000000;font-size:medium;	border:thin solid #DDDDFF; }
 .thCalHeader { background-color:#227447;font:arial;font-weight:bold;color:white;font-size:x-small;	border:thin solid #DDDDFF; height:25px;}
 .tdToday
 {
	text-align:left;
	/*background-color:#DDFFDD;*/
	background-color:#227447;
	font:arial;
	font-weight:bold;
	color:white;
	font-size:x-small;
	border:thin solid #DDAAFF;
 }
 .tdToday a
 {
   color: white;
 }
 .dayTextLarge
 {
 	background-color : #227447;
 	height:20px;
 	font-size: medium;
  color: white;
 }
 .dayTextLarge a
 {
  font-size: medium;
  color: white;
 }
/* .dayTextsmall a
 {
  color: white;
 }*/
 a{color:#FFF}
 h2 {text-align:center}
 div a {color:#000}
 span{
   vertical-align: top;
   width:4em;

 }
 .w2{
   letter-spacing:2em; /*如果需要y个字两端对齐，则为(x-y)/(y-1),这里是（4-2）/(2-1)=2em */
   margin-right:-2em;
 }
-->
</style>
